create TABLE INSTRUCTOR(
    INSTRUCTOR_SEQ_NO INTEGER PRIMARY KEY,
    INSTRUCTOR_ID VARCHAR(30) PRIMARY KEY,
    INSTRUCTOR_NAME VARCHAR(30),
    INSTRUCTOR_PASSWORD VARCHAR(15),
    INSTRUCTOR_LEVEL CHAR(1),
    STUDENT_ID_LIST JSON,
    INSTRUCTOR_TASK JSON
)

create sequence  INSTRUCTOR_SEQ_NO
start with 1
increment by 1;