create TABLE INSTRUCTOR(
    INSTRUCTOR_SEQ_NO INTEGER,
    INSTRUCTOR_ID VARCHAR(30) PRIMARY KEY,
    NAME VARCHAR(30),
    PASSWORD VARCHAR(15),
    LEVEL CHAR(1),
    INSTRUCTOR_TASK JSON
);

create sequence  INSTRUCTOR_SEQ_NO
start with 1
increment by 1;