create TABLE STUDENT(
    STUDENT_SEQ_NO INTEGER PRIMARY KEY,
    STUDENT_ID VARCHAR(30) PRIMARY KEY,
    STUDENT_NAME VARCHAR(30),
    STUDENT_PASSWORD VARCHAR(15),
    STUDENT_LEVEL CHAR(1),
    STUDENT_INSTRUCTOR_ID VARCHAR(30),
    STUDENT_TASK JSON
)

create sequence  STUDENT_SEQ_NO
start with 1
increment by 1;