create TABLE INSTRUCTOR(
    INSTRUCTOR_SEQ_NO INTEGER,
    INSTRUCTOR_ID VARCHAR(30) PRIMARY KEY,
    NAME VARCHAR(30),
    PASSWORD VARCHAR,
    LEVEL CHAR(1)
);

create sequence  INSTRUCTOR_SEQ_NO
start with 1
increment by 1;